# Generated by Django 2.2.16 on 2020-10-05 08:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=2000)),
                ('desc1', models.CharField(max_length=5000)),
                ('desc2', models.CharField(max_length=5000)),
                ('desc3', models.CharField(max_length=5000)),
                ('desc4', models.CharField(max_length=5000)),
                ('location', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('lot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('slug', models.SlugField(blank=True, max_length=5000, null=True, unique=True)),
                ('photo_main', models.CharField(max_length=2000)),
                ('photo_1', models.CharField(max_length=2000)),
                ('photo_2', models.CharField(max_length=2000)),
                ('photo_3', models.CharField(max_length=2000)),
                ('photo_4', models.CharField(max_length=2000)),
                ('photo_5', models.CharField(max_length=2000)),
                ('photo_6', models.CharField(max_length=2000)),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor')),
            ],
        ),
    ]
