# Generated by Django 2.2.16 on 2020-10-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='realtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.Realtor'),
        ),
    ]
