# Generated by Django 2.2.16 on 2020-10-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201002_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.CharField(default=12, max_length=2000),
            preserve_default=False,
        ),
    ]
