# Generated by Django 2.2.16 on 2020-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=2000)),
                ('desc1', models.CharField(max_length=5000)),
                ('desc2', models.CharField(max_length=5000)),
                ('desc3', models.CharField(max_length=5000)),
                ('desc4', models.CharField(max_length=5000)),
            ],
        ),
    ]
