# Generated by Django 2.2.16 on 2020-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_sitemetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemetadata',
            name='location',
            field=models.CharField(default=12, max_length=5000),
            preserve_default=False,
        ),
    ]
