# Generated by Django 2.2.16 on 2020-10-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_sitemetadata_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=5000, null=True, unique=True),
        ),
    ]
